# Funciones y Namespaces


## 1. Funciones

Una función es un bloque de código que sólo corre cuando es llamado.

In [1]:
def par_o_impar(numero):
    if numero %2 == 0:
        print('Es par')
    else:
        print('Es impar')

Notar que si ejecutamos la celda no ocurre nada apreciable. Si llamamos a la función

In [2]:
par_o_impar

<function __main__.par_o_impar(numero)>

Python nos dice, de una forma no muy clara, que se trata de una función. Las funciones se llaman con paréntesis:

In [388]:
import pandas as pd
pd.DataFrame([1,2,22,3,54,43,23])[0].map(par_o_impar)

Es impar
Es par
Es par
Es impar
Es par
Es impar
Es impar


0    None
1    None
2    None
3    None
4    None
5    None
6    None
Name: 0, dtype: object

Y en este caso, arroja un error porque falta un argumento, `numero`. Las dos siguientes son equivalentes:

In [4]:
par_o_impar(numero = 9)
par_o_impar(9)

Es impar
Es impar


Al tener un solo argumento, en este caso no hay mucho lugar a confusión, pero las funciones pueden tener muchos argumentos:

In [5]:
def division(dividendo, divisor):
    print(dividendo/divisor)

Entonces podemos llamar a la función pasándole los argumentos en orden, o explicitando el valor de cada argumento:

In [6]:
division(4,2)
division(divisor = 4, dividendo = 2)  #notar que asi no nos tenemos que preocupar por el orden

2.0
0.5


También, pueden tener argumentos *por default*, que si no explicitamos, toman un valor predefinido:

In [7]:
def division(dividendo, divisor = 2):
    print(dividendo/divisor)

In [8]:
division(9)
division(9, 3) 
division(dividendo = 9, divisor = 3) # Mejor opción para cuando quiero volver a leer el código
division(9, divisor = 3) 

4.5
3.0
3.0
3.0


### 1.1 `return`

Las funciones pueden devolver resultados

In [287]:
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar # return me devuelve el resultado, me devuelve el objeto (diferente a print)

In [288]:
resultado_division = division(9,3)

In [289]:
print(resultado_division)

3.0


Y, si lo necesitamos, podemos hacer que devuelvan más de un resultado

In [12]:
def division_y_producto(numero_1,numero_2):
    div = numero_1/numero_2
    prod = numero_1*numero_2
    return div, prod

### Son equivalentes
# def division_y_producto(numero_1,numero_2):
#     return numero_1/numero_2, numero_1*numero_2

In [13]:
resultados = division_y_producto(10,5)
print(resultados)

(2.0, 50)


Notar la diferencia

In [14]:
resultado_1, resultado_2 = division_y_producto(10,5)
print(resultado_1, resultado_2)

2.0 50


### 2. Namespaces and Scope

Encontrar la diferencia entre las siguientes celdas:

In [308]:
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50)) # divisor = 2, predefinido 
print(divisor) # divisor solo existe en el local, no afuera, por eso el error

25.0


NameError: name 'divisor' is not defined

In [301]:
divisor = 5 # Redefinimos divisor
def division(dividendo):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

10.0
5


In [17]:
divisor = 5
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

25.0
5


**Investigar:** ¿qué es una variable global?¿Y una variable local?¿Qué es un Namespace?

### 3. Funciones Lambda (Anónimas)

Una función `lambda` es una forma conveniente de crear una función en una sola línea. También se las conoce como funciones anónimas, ya que no suelen tener nombre.

In [294]:
lambda_division = lambda x,y: x/y
lambda_division(80,10)

8.0

Algunas características:
1. Pueden tener cualquier cantidad de argumentos, pero solo una expresión
1. No se les suele poner nombre como hicimos, de hecho es raro utilizarlas de esa forma.
1. No necesitan un `return`
1. Muy cómodas para crear funciones rápido.
1. En general, las veras combinadas con funciones como `map()`, `filter()`, `apply()`, `applymap()`, etc.

Existen algunas diferencias sutiles entre una función creada con `def` y una función lambda, pero para nuestros objetivos basta con saber que una función lambda es una forma rápida de crear funciones sencillas.

### 4. Documentando funciones

Cuando creemos funciones es conveniente documentarlas, así si volvemos meses después a nuestro código, o se lo compartimos a alguien, podemos entender qué hace sin tener que leer y entenderlo completamente. Es decir, de la misma forma que hacemos con muchas de las funciones de las librerías que venimos usando. Hay muchos formatos para documentar una función, pero en general incluyen: qué hace la función, cuales son sus argumentos, y cuáles son sus returns. A veces, también algún ejemplo mostrando cómo se usa. El grado de detalle depende del tiempo y de la complejidad de la función. Recomendamos siempre documentar las funciones, aunque sea de forma breve.

Dejamos un formato de documentación a modo de ejemplo. En general, se estila documentar en inglés, pero vamos a hacer una excepción.

In [295]:
def division_y_producto(numero_1,numero_2):
    '''
    Dados dos numeros, devuelve su division
    y su producto.
    
    Arguments:
    numero_1 -- dividendo, primer multiplicando
    numero_2 -- divisor, segundo multiplicando
    
    Returns:
    div -- la division entre los dos numeros
    prod -- el producto entre los dos numeros
    '''
    
    div = numero_1/numero_2
    prod = numero_1*numero_2
    return div, prod

Notar que si ahora ponemos `help()` de nuestra función, devuelve la documentación que creamos.

In [20]:
help(division_y_producto)

Help on function division_y_producto in module __main__:

division_y_producto(numero_1, numero_2)
    Dados dos numeros, devuelve su division
    y su producto.
    
    Arguments:
    numero_1 -- dividendo, primer multiplicando
    numero_2 -- divisor, segundo multiplicando
    
    Returns:
    div -- la division entre los dos numeros
    prod -- el producto entre los dos numeros



También, si usamos `shift`+`tab` como hacemos con las otras funciones de las librerías.

### Challenge

1. Crea una función que tome como entrada dos arreglos de Numpy. Luego, que chequee si tienen el mismo tamaño; si no es así, que imprima un mensaje indicando que no tienen el mismo tamaño. Si tienen el mismo tamaño, que haga las siguientes operaciones:
    1. Crear un nuevo arreglo con el resultado de las resta de los dos arreglos originales.
    1. Elevar al cuadrado ese arreglo.
    1. Sumar todos los elementos y dividir por la cantidad de elementos.
    1. Devuelva la raiz de ese resultado.

In [379]:
def RMSE(arreglo_1, arreglo_2):
    if len(arreglo_1) == len(arreglo_2):
        resta = arreglo_1 - arreglo_2
        cuadrado = resta ** 2
        suma = sum (cuadrado)
        suma_2 = suma/ len(resta)
        raiz = suma_2 ** (1/2)
        return (raiz)
    else:
        print("Los arreglos no tienen el mismo tamaño")  

Testeamos el resultados

In [380]:
np.random.seed(10)  # que hace esta linea?
arreglo_1 = np.random.randint(-10,10, 50)
arreglo_2 = np.random.randint(-10,10, 50)
print(arreglo_1)
print(arreglo_2)

[ -1  -6   5 -10   7   6   7  -2  -1 -10   0  -2  -6   9   6  -6   5   1
   1  -9  -2  -6   4   7   9   3  -5   3   9   3   2  -9  -6   8   3   1
   0  -1   5   8   6  -3   1   7   4  -3   1  -9 -10   2]
[ -5  -6  -3   8   2  -8  -2   5   3   5  -4   0   1   6   2 -10   7   5
   2  -2   0   3   1  -9   8   3  -2  -1  -5 -10   8  -7   6   8   6   4
   9   5   9   7   8   4   6   0   7 -10   7  -1   6  -1]


In [381]:
RMSE(arreglo_1, arreglo_2)

7.487322618933954

Debería dar como resultado 7.48732

In [382]:
np.random.seed(10)  # que hace esta linea?
arreglo_1 = np.random.randint(-10,10, 25)
arreglo_2 = np.random.randint(-10,10, 50)
print(arreglo_1)
print(arreglo_2)

[ -1  -6   5 -10   7   6   7  -2  -1 -10   0  -2  -6   9   6  -6   5   1
   1  -9  -2  -6   4   7   9]
[  3  -5   3   9   3   2  -9  -6   8   3   1   0  -1   5   8   6  -3   1
   7   4  -3   1  -9 -10   2  -5  -6  -3   8   2  -8  -2   5   3   5  -4
   0   1   6   2 -10   7   5   2  -2   0   3   1  -9   8]


In [383]:
RMSE(arreglo_1, arreglo_2)

Los arreglos no tienen el mismo tamaño


Debería dar como resultado un mensaje indicando que no tienen el mismo tamaño.

2. Documentar brevemente la función creada.

In [384]:
def RMSE(arreglo_1, arreglo_2):
    '''
    Dados dos arreglos, crea un nuevo arreglo con el resultado
    de las resta de los dos arreglos originales, eleva al cuadrado ese arreglo,
    suma todos los elementos y divide por la cantidad de elementos.
    Devuelva la raiz de ese resultado. 
    
    Arguments:
    arreglo_1 -- primer arreglo
    arreglo_2 -- segundo arreglo
    
    Returns:
    raiz -- resultado
    '''
    if len(arreglo_1) == len(arreglo_2):
        resta = arreglo_1 - arreglo_2
        cuadrado = resta ** 2
        suma = sum (cuadrado)
        suma_2 = suma/ len(resta)
        raiz = suma_2 ** (1/2)
        return (raiz)
    else:
        print("Los arreglos no tienen el mismo tamaño") 

In [385]:
help (RMSE)

Help on function RMSE in module __main__:

RMSE(arreglo_1, arreglo_2)
    Dados dos arreglos, crea un nuevo arreglo con el resultado
    de las resta de los dos arreglos originales, eleva al cuadrado ese arreglo,
    suma todos los elementos y divide por la cantidad de elementos.
    Devuelva la raiz de ese resultado. 
    
    Arguments:
    arreglo_1 -- primer arreglo
    arreglo_2 -- segundo arreglo
    
    Returns:
    raiz -- resultado



### 5. Ejercitación - Generala

¡Vamos a jugar a la generala! Para los que no la conocen: es un juego de dados. En este juego tienes 3 tiradas y 5 dados para formar distintas combinaciones (escalera, full, etc). Después de cada tiro, puedes decidir cuántos y cuáles dados dejar en la mesa y cuáles volver a tirar. De esta forma, tienes tres tiradas para lograr alguna de las combinaciones. La combinación que más puntos te da es la generala, que se obtiene cuando los 5 dados devuelven el mismo número.

El jugador puede tomar decisiones y plantear una estrategia en este juego, pero la última palabra la tiene el azar. Un buen matemático podría calcular las probabilidades de cada combinación, e ir calculando cómo se modifican estas probabilidades a medida que va dejando - o no - dados sobre la mesa.

En nuestro caso, lo que haremos es simular una generala simplificada - el único objetivo es obtener la generala, cinco dados iguales. Para ello, programarás una serie de funciones que te ayudarán a jugar a este juego. Con estas funciones, podrás responder varias preguntas, entre ellas:

1. ¿Cuán probable es obtener una generala en la primera tirada?
1. ¿Cuán probable es obtener una generala con dos tiradas?
1. ¿Cuán probable es obtener una generala luego de las tres tiradas?
1. ¿Qué es más problable: obtener una generala con tres tiradas y cinco dados o cuatros tiradas y seis dados?

y las que se te ocurran. ¡Manos a la obra!

**Importante:** todas las funciones que te pedimos definir acá se resuelven en pocas líneas de código. NumPy y Google forman un gran equipo. Nosotros te dejamos casos de testeo para tus funciones. Resuélvelos con un/a compañero/a, recuerda pensar el problema (escribiéndolo en un papel, hablándolo con alguien) y luego programa. ¡Verás que no son tan difíciles!

**Importante dos:** este desafío fue propuesto por *Ernesto Mislej* en el grupo de Facebook *Data Science Argentina*.¡Recomendamos unirse a éste o a otro grupo sobre Ciencia de Datos!

1. Crea la función `tirar_n_dados`. Debe tomar como argumento por defecto `n = 5`, pero tiene que funcionar correctamente para otros valores de `n`.

In [391]:
import numpy as np
from numpy import random

def tirar_n_dados(n = 5):
    return random.randint(6, size = n)

In [392]:
tirar_n_dados()

array([5, 0, 1, 1, 5])

2. Crea la función `es_generala`. Esta función toma como entrada los resultados de `tirar_n_dados` y devuelve `True` si es generala y `False` si no lo es.

In [132]:
#def es_generala(result):
#   if result[0] == result[1] == result[2] == result[3] == result[4]:
#        return True
#    else:
#        return False

In [393]:
# Opción fácil 
def es_generala(dados):
    return len(set(dados)) == 1

In [394]:
### TESTEO UNO
array_de_prueba = np.array([2,5,5,5,5])
print(es_generala(array_de_prueba))

False


In [395]:
### TESTEO DOS
for _ in range(10000):
    tirada_dados = tirar_n_dados(n = 5)
    if es_generala(tirada_dados):
        print(tirada_dados)

[5 5 5 5 5]
[1 1 1 1 1]
[5 5 5 5 5]
[2 2 2 2 2]


3. Crea una función `seleccionar_mayoria` que, dada una tirada de n dados, devuelve cuál es la moda de los resultados y con qué frecuencia. Dos consideraciones: 
    * Si los n resultados son distintos, es indistinto cuál valor devuelve.
    * Si hay más de un valor posible para devolver - por ejemplo, en la tira `[1, 1, 2, 2, 3]` -, es indistinto cuál valor elige.
    
    Tal vez te sirva saber que estas consideraciones se resuelven automáticamente si utilizas algunas herramientas de NumPy, como `np.unique()`, `np.argmax()` y alguna más.

In [396]:
def seleccionar_mayoria(dados):
    valores, frecuencia = np.unique(dados, return_counts = True)
    maximo = valores[np.where(frecuencia == max(frecuencia))][0]
    return maximo, max(frecuencia)

In [397]:
# TESTEO UNO
array_de_prueba = np.array([1,1,1,5,5])
print(seleccionar_mayoria(array_de_prueba))
### Debería dar como resultado (1,3)

# TESTEO DOS
array_de_prueba = np.array([5,3,2,1,6])
print(seleccionar_mayoria(array_de_prueba))
### Debería dar como resultado (algun numero salvo el 4,1)

(1, 3)
(1, 1)


Acá la cosa se empieza a poner áspera, pero tampoco tanto. Veamos algunas situaciones:

* Supongamos que en una primera tirada obtienes como resultado `[1, 1, 2, 5, 3]`. En ese caso, te debes quedar con los dados `[1, 1]` y volver a tirar los otros tres dados. Si cuando tiras los tres dados obtienes tres valores iguales **distintos** de los que habías reservado, la mejor estrategia es quedarte con esos tres dados y volver a tirar los otros dos. 
* Supongamos que en una primera tirada obtienes como resultado `[1, 1, 2, 5, 3]`. En ese caso, te debes quedar con los dados `[1, 1]` y volver a tirar los otros tres dados. Si cuando tiras los tres dados obtienes `[1, 1, 5]` debes poder sumar a los dados que apartaste esos dos `1`.

Entonces:


4. Crea una función `jugar` tome como argumentos `n_tiradas` con argumento por defecto `3` y `dados_total` con argumento por defecto `5` y que, utilizando las funciones que definiste antes, juegue a la generala. La función debe devolver un arreglo con las n-tiradas realizadas y un índice indicando en qué tirada logró la generala si corresponde (si no logra la generala, debe devolver un valor que indique que no se logró la generala, ¿cuál se te ocurre?). 
    
    Te vamos a dejar un esqueleto bastante armado para esta función, pero si quieres arrancar desde cero, obviamente puedes hacerlo. Para completarlo, ten en cuenta que luego de cada tirada debes dejar algunos dados en la mesa, `dados_mesa`, y volver a tirar otros, `dados_nuevos`. La cantidad de dados nuevos que debes tirar se decide dinámicamente en cada ciclo del loop. Cuando decides qué dados deben quedar sobre la mesa, debes mirar tanto los dados que ya estaban sobre la mesa como los que acabas de tirar, `todos_dados`.

In [403]:
def jugar(n_tiradas = 3, dados_total= 5):
    # Numero de dados a tirar inicialmente
    n_dados = dados_total 
    
    # Dados en la mesa inicialmente
    dados_mesa = np.array([]) 
    
    # Donde guardamos las tiradas
    tiradas = {} 
    
    # Numero de tirada exitosa, en la que se logra la generala
    # Inicializar en un valor que indique que NO se obtuvo generala.
    # Si luego se obtiene una generala, se modificará
    tirada_exitosa = -1
    
    # Contamos cuantas tiradas hicimos hasta ahora
    contador_tiradas = 0
    
    while (contador_tiradas < n_tiradas) and tirada_exitosa == -1:
        # Tiramos los dados
        dados_nuevos = tirar_n_dados(n = n_dados)
        
        # Combinamos los dados recien tirados con los que ya estan en la mesa
        todos_dados = np.concatenate((dados_mesa, dados_nuevos))
        
        # Guardamos tirada
        tiradas[contador_tiradas] = dados_nuevos
        
        # Nos fijamos si es generala
        if es_generala(todos_dados):
            # Si es, modificamos el valor de tirada exitosa.
            # Esto debe cortar el loop.
            tirada_exitosa = 0
        else:
            # Si no es generala, sigue tirando 
            # Se fija qué dados debe dejar en la mesa
            maximo, frecuencia = seleccionar_mayoria(todos_dados)
            dados_mesa = np.repeat(maximo, frecuencia)
            
            # Calcula cuántos dados volver a tirar
            n_dados = 5 - len(dados_mesa)
        
        # Suma al contador de tiradas
        contador_tiradas = contador_tiradas + 1
    return tiradas, tirada_exitosa

In [404]:
# TESTEO
for i in range(200):
    tiradas, tirada_exitosa = jugar(3, 5)
    if tirada_exitosa >=0:
        print(tiradas, tirada_exitosa)

{0: array([1, 4, 1, 1, 1]), 1: array([5]), 2: array([1])} 0
{0: array([2, 0, 0, 0, 2]), 1: array([3, 0]), 2: array([0])} 0
{0: array([3, 0, 3, 1, 3]), 1: array([2, 3]), 2: array([3])} 0
{0: array([2, 1, 1, 4, 5]), 1: array([5, 1, 1]), 2: array([1])} 0
{0: array([2, 3, 2, 1, 0]), 1: array([5, 3, 2]), 2: array([2, 2])} 0
{0: array([0, 2, 3, 5, 4]), 1: array([0, 5, 0, 1]), 2: array([0, 0])} 0


¿Estás contento/a con el código?¿Está bien hecho?¿Se te ocurre alguna situación que no haya sido considerada o donde pueda fallar? Siempre es importante ser crítico con el código desarrollado (y con la metodología en general) en busca de puntos débiles. Siempre se puede programar mejor. De hecho, hay un montón de buenas costumbres cuando programamos funciones que hemos dejado de lado, como por ejemplo, chequear que a nuestra funciones les lleguen los argumentos correctos. Por ejemplo, si nuestra función debe recibir como argumento un arreglo de NumPy de cierto shape, no está demás chequearlo.

Ahora sí, es hora de jugar con estas funciones. Elije algunas de las preguntas e intenta responderla, o genera alguna propia y fíjate si lo que hicimos te sirve para responderla. Nosotros elegimos responder qué generala es más probable, si tres tiros y cinco dados o cuatro tiros y seis dados, que te la daremos junto con el resuelto de este notebook.